### ISSUE TITLE
onMovieClicked not work ?

### ISSUE THREAD

**Issue by CMingTseng** [yasinkacmaz/jetflix#149]
Dear Sir

I click Image

but  onMovieClicked not work ?

can not navigateTo  MovieDetail

THX

**Comment by yasinkacmaz** [comment]
Dear sir,
this is a project which uses latest alpha and beta versions.
Problems always will be here, as I have free time I will try to fix them and learn about updates.
Other than that this is my personal side project.
I will look when I have free time.

**Comment by CMingTseng** [comment]
Dear Sir

Sorry 

i just find Ref project & know best way 

sorry 

OK

i konw why can not go to  MovieDetailPreview 

because not Navigator 

but  if use compose Navigator  @ compose 1.0.0-beta08

must upgrade navigation-compose to 2.4.0-alpha02 

 navigation-compose  1.0.0-alpha10 base on  compose 1.0.0-beta04
 
 THX
