### ISSUE TITLE
Laggy List

### ISSUE THREAD

**Issue by cormen3** [yasinkacmaz/jetflix#163]
There is an obvious performance issue during scrolling the list, even in release mode It is laggy. I think It comes from LazeVerticalGrid when cell number is greater than 1

**Comment by yasinkacmaz** [comment]
Hello @cormen3. This issue is on my to-do list for a while, did you try it on a real device? On the emulator, the list seems laggy no matter what I do. When using a real device it is not laggy for me.

**Comment by cormen3** [comment]
Actually, I downloaded release apk and run it on my real device (Xiaomi Redmi note 7). It was laggy

**Comment by cormen3** [comment]
https://user-images.githubusercontent.com/20010282/140041872-9ce7cf0c-69f2-493b-8bc3-aaaa13249450.mp4

you can see in this video
