### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [yasinkacmaz/jetflix#185]
I've searched the repo, but couldn't find any information concerning the license used by this project. What license does apply to your code? Could you please add that information? Thanks in advance!

**Comment by yasinkacmaz** [comment]
I don't have a licence.

**Comment by IzzySoft** [comment]
That means "all rights reserved" and might scare away potential contributors as well as potential users. Why not choose one that fits? If you don't care, that could even be the WTFPL ([Do What The F*ck You Want To Public License](https://spdx.org/licenses/WTFPL.html)). Otherwise, you can e.g. find [some good recommendations here](https://docs.codeberg.org/getting-started/licensing/). It's your software, so the choice is yours :smiley:

**Comment by yasinkacmaz** [comment]
The thing is I didn’t think about it, just made the repo as open. I am not even sure whether it is required.

**Comment by IzzySoft** [comment]
If it's "required" depends on many things. If you want your app being "F/LOSS" – i.e. free, libre, open-source software – it indeed ***is*** required, as without a license it's just "source available" and neither free/libre (as "no license" implicitly means "all rights reserved": you didn't grant usage) nor "open" (as due to the "all rights reserved" nobody except you is really "open" to fully use it).

So it's fully up to what you want it to be. If you want others to "freely participate" (actively or passively), you should choose a license. Depending on how permissive you want it to be, and how much "rights" you want to preserve, you can choose a rather permissive license (PublicDomain, WTFPL, Apache-2.0, MIT, BSD-*-Clause). If you want to avoid someone else makes profit from your work without giving back, pick something on the more restrictive end (e.g. AGPL-3.0 – so-called "copy-left" licenses including a clause that all derivative works must use the same license, to put it simple).

**Comment by IzzySoft** [comment]
So anydecision on this, @yasinkacmaz? I'd really like to include your app with [my repo](https://apt.izzysoft.de/fdroid) – but cannot without a license (to my experience, it rarely is "added soon" thereafter, and users of my repo expect FOSS, which means it must have a FOSS license).

**Comment by yasinkacmaz** [comment]
Hello @IzzySoft sorry for the delayed response. I've included **MIT Licence** for this repository. I guess now you can use it safely.

**Comment by IzzySoft** [comment]
Thanks a lot! I've just integrated it with my catalog, it will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.yasinkacmaz.jetflix) with the next sync around 6 pm UTC tomorrow.
