### ISSUE TITLE
I want to translate

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [yasinkacmaz/jetflix#192]
I have seen that the app has to be translatable, but in German, for example, a lot is not translated.

Is there a link somewhere on github so that I know what I can translate?

**Comment by yasinkacmaz** [comment]
Hi @mondlicht-und-sterne the app is not translatable. When you select a language it uses **ISO** code to fetch **TMDB** movies with that language. You can add a translation for your favorite movie on the **TMDB** website.
