### ISSUE TITLE
Add: Movie Stream Sources ( webview or internal player )

### ISSUE THREAD

**Issue by OshekharO** [yasinkacmaz/jetflix#228]
https://sora.is-really.cool/

Or 

https://documenter.getpostman.com/view/18986031/UVXdNeFD

**Comment by yasinkacmaz** [comment]
Hello @OshekharO, Jetflix is a project to try out Jetpack Compose android UI Toolkit.
Unfortunately, for now, I don't intend to add any feature for streaming the movies. Obviously for legal reasons and not detouring from the main scope of this repository.

**Comment by OshekharO** [comment]
> Hello @OshekharO, Jetflix is a project to try out Jetpack Compose android UI Toolkit. Unfortunately, for now, I don't intend to add any feature for streaming the movies. Obviously for legal reasons and not detouring from the main scope of this repository.

Ok
