### ISSUE TITLE
Filtering and sorting not working

### ISSUE THREAD

**Issue by TB1333** [yasinkacmaz/jetflix#303]
Filter and sorting of data don't work at all. I open the filter menu, set my wished filter options and ...  nothing happens.
Only thing I can actually do in the app is opening movies directly by clicking on their preview card and searching in the search bar for specific movies.

Searching for movies is operational but when I have performed one search, I have to clear the search bar to get back to the homescreen with the movies displayed by default. 

When I open a movie's information read it and go back to thr overview screen I still see the previous search results but there is no way to go back to "homescreen" because the search bar has been cleared automatically and there is nothing I can do myself. Only remedy is to perform a new search and clear the search bar afterwards.

**Comment by yasinkacmaz** [comment]
Hey @TB1333! Thanks so much for bringing this up.
I took a look at the search and filter issues you mentioned, and it seems like these PRs should take care of them:

[#305](https://github.com/yasinkacmaz/jetflix/pull/305) (Fix for search behavior)
[#308](https://github.com/yasinkacmaz/jetflix/pull/308) (Fix for filter changes)

Feel free to check them out! Also, attaching the release APK containing the fixes in case you'd like to try it:
[app-release.apk.zip](https://github.com/user-attachments/files/17160726/app-release.apk.zip)
